AWSTemplateFormatVersion: "2010-09-09"

Description: Security groups

Parameters:
  vpc:
    Type: String

Resources:
  default:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress: 
        Description: Port 80 inbound
        CidrIp: 172.31.0.0/20
        FromPort: 80
        IpProtocol: http
        VpcId: !Ref vpc
      SecurityGroupIngress: 
        Description: Port 443 inbound
        CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: https
        VpcId: !Ref vpc
      SecurityGroupEgress: 
        Description: Default security group
        IpProtocol: all
        VpcId: !Ref vpc