AWSTemplateFormatVersion: "2010-09-09"

Description: Security groups

Resources:

  vpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://bucket-of-warunek.s3.amazonaws.com/cloudformation/vpc.yaml" 
      Parameters: 
        vpc: 
          Type: String
          Ref: vpc
  
  default:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress: 
        Description: Port 80 inbound
        CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: http
        VpcId: !Ref vpcStack
      SecurityGroupIngress: 
        Description: Port 443 inbound
        CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: https
        VpcId: !Ref vpcStack
      SecurityGroupEgress: 
        Description: Default security group
        IpProtocol: all
        VpcId: !Ref vpcStack